### ISSUE TITLE
Docker Backup Volumes  

### ISSUE THREAD

**Issue by zinderud** [samilsam/kanka#10]
inceleme listesi

[bivac]( https://github.com/camptocamp/bivac)

**Comment by zinderud** [comment]
```
docker run -d --name bivac -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e AWS_ACCESS_KEY_ID=XXXX \
  -e AWS_SECRET_ACCESS_KEY=XXXXXX \
  -e BIVAC_TARGET_URL=s3:my-bucket \
  -e RESTIC_PASSWORD=foo \
  -e BIVAC_SERVER_PSK=toto \
  -e BIVAC_AGENT_IMAGE=camptocamp/bivac:stable \
  -p 8182:8182 \
```
camptocamp/bivac:stable manager

You can easily deploy Bivac with a simple docker-compose.yml:
```

version: '2'
services:
  bivac:
    image: camptocamp/bivac:stable
    command: manager
    ports:
      - "8182:8182"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      AWS_ACCESS_KEY_ID: XXXX
      AWS_SECRET_ACCESS_KEY: XXXXXX
      RESTIC_PASSWORD: foo
      BIVAC_TARGET_URL: s3:my-bucket
      BIVAC_SERVER_PSK: toto
      BIVAC_AGENT_IMAGE: camptocamp/bivac:stable
```
